name: Filename Validation

on: [push]

jobs:
  validate-filename:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Validate Filenames
      run: |
        for file in $(find . -type f); do
          python filename_validator.py "$file"
        done
